apiVersion: v1
kind: Service
metadata:
  name: cloudpose-service
  labels:
    app: cloudpose
    component: web-service
spec:
  # 使用NodePort类型以便外部访问
  type: NodePort
  selector:
    app: cloudpose
  ports:
  - port: 60001        # Service内部端口
    targetPort: 60001   # Pod容器端口
    nodePort: 30001     # 外部访问端口（必须在30000-32767范围内）
    protocol: TCP
    name: http
  
  # 会话亲和性（可选）
  # sessionAffinity: ClientIP

---
# 可选：创建一个LoadBalancer类型的服务（如果云平台支持）
apiVersion: v1
kind: Service
metadata:
  name: cloudpose-loadbalancer
  labels:
    app: cloudpose
    component: load-balancer
spec:
  type: LoadBalancer
  selector:
    app: cloudpose
  ports:
  - port: 80           # LoadBalancer对外端口
    targetPort: 60001  # Pod容器端口
    protocol: TCP
    name: http

---
# 可选：创建Ingress资源（如果需要域名访问）
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudpose-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: cloudpose.local  # 替换为你的域名
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudpose-service
            port:
              number: 60001 
